// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(message: string) : Promise<Result<PingResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendRequest(requestId: string, spec: RequestSpec) : Promise<Result<ResponseSpec, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_request", { requestId, spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRequest(requestId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_request", { requestId });
},
async openWorkspace(path: string) : Promise<Result<WorkspaceInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_workspace", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createWorkspace(parentDir: string, name: string) : Promise<Result<WorkspaceInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_workspace", { parentDir, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeWorkspace() : Promise<void> {
    await TAURI_INVOKE("close_workspace");
},
async refreshWorkspace() : Promise<Result<WorkspaceInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_workspace") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCollection(name: string) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_collection", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(parentPath: string, name: string) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { parentPath, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRequest(parentPath: string, request: RequestFile) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_request", { parentPath, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameNode(path: string, newName: string) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_node", { path, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async duplicateNode(path: string) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("duplicate_node", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteNode(path: string) : Promise<Result<WorkspaceInfo, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_node", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadRequest(path: string) : Promise<Result<RequestFile, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_request", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveRequest(path: string, request: RequestFile) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_request", { path, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async moveNode(path: string, newParentPath: string, order: string[]) : Promise<Result<Mutation, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("move_node", { path, newParentPath, order }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Error returned from every Tauri command. Serializes to
 * `{ "kind": "InvalidInput", "message": "..." }`, so the UI can switch on `kind`.
 */
export type AppError = { kind: "Io"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "Internal"; message: string } | { kind: "Network"; message: string } | { kind: "Timeout"; message: string } | { kind: "Cancelled"; message: string } | { kind: "NotFound"; message: string } | { kind: "Unsupported"; message: string }
export type BodyEncoding = "utf8" | "base64"
export type BodyFile = { mode: BodyMode; json?: string; raw?: string; rawMime?: string; form?: KeyValue[] }
export type BodyMode = "none" | "json" | "raw" | "form"
export type HeaderEntry = { name: string; value: string }
export type KeyValue = { key: string; value: string; enabled: boolean }
/**
 * Result of a tree mutation: the affected node's (new) path plus a fresh tree.
 */
export type Mutation = { path: string; info: WorkspaceInfo }
/**
 * One row of the flattened, depth-first tree.
 */
export type NodeEntry = { kind: NodeKind; id: string; name: string; 
/**
 * Relative to the workspace root, `/` separated.
 */
path: string; parentPath: string | null; depth: number; method: string | null }
export type NodeKind = "collection" | "folder" | "request"
export type PingResponse = { reply: string; appVersion: string }
export type RequestBody = { type: "none" } | { type: "json"; content: string } | { type: "raw"; content: string; mime: string } | { type: "formUrlEncoded"; fields: KeyValue[] }
/**
 * <name>.request.json. Mirrors the editor state so nothing is lost between body modes.
 */
export type RequestFile = { schemaVersion: number; id: string; name: string; method: string; url: string; params?: KeyValue[]; headers?: KeyValue[]; body: BodyFile; settings: RequestSettings }
export type RequestSettings = { 
/**
 * 0 means no timeout.
 */
timeoutMs: number; followRedirects: boolean }
export type RequestSpec = { method: string; 
/**
 * Final URL including the query string.
 */
url: string; headers: KeyValue[]; body: RequestBody; settings: RequestSettings }
export type ResponseSpec = { status: number; statusText: string; httpVersion: string; headers: HeaderEntry[]; body: string; bodyEncoding: BodyEncoding; bodyTruncated: boolean; sizeBytes: number; durationMs: number; finalUrl: string; contentType: string | null }
export type WorkspaceInfo = { id: string; root: string; name: string; nodes: NodeEntry[]; 
/**
 * Files that were skipped (invalid JSON, newer schema, ...).
 */
warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
