// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async ping(message: string) : Promise<Result<PingResponse, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping", { message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendRequest(requestId: string, spec: RequestSpec) : Promise<Result<ResponseSpec, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_request", { requestId, spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelRequest(requestId: string) : Promise<boolean> {
    return await TAURI_INVOKE("cancel_request", { requestId });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Error returned from every Tauri command. Serializes to
 * `{ "kind": "InvalidInput", "message": "..." }`, so the UI can switch on `kind`.
 */
export type AppError = { kind: "Io"; message: string } | { kind: "InvalidInput"; message: string } | { kind: "Internal"; message: string } | { kind: "Network"; message: string } | { kind: "Timeout"; message: string } | { kind: "Cancelled"; message: string }
export type BodyEncoding = "utf8" | "base64"
export type HeaderEntry = { name: string; value: string }
export type KeyValue = { key: string; value: string; enabled: boolean }
export type PingResponse = { reply: string; appVersion: string }
export type RequestBody = { type: "none" } | { type: "json"; content: string } | { type: "raw"; content: string; mime: string } | { type: "formUrlEncoded"; fields: KeyValue[] }
export type RequestSettings = { 
/**
 * 0 means no timeout.
 */
timeoutMs: number; followRedirects: boolean }
export type RequestSpec = { method: string; 
/**
 * Final URL including the query string.
 */
url: string; headers: KeyValue[]; body: RequestBody; settings: RequestSettings }
export type ResponseSpec = { status: number; statusText: string; httpVersion: string; headers: HeaderEntry[]; body: string; bodyEncoding: BodyEncoding; bodyTruncated: boolean; sizeBytes: number; durationMs: number; finalUrl: string; contentType: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
